14 basic css ui
CentralLaserFacility/ADPixci pull request #15
Opened 2020-09-30 05:14 UTC by subindev-d

created a css screen to stream the images, added binning settings control

2020-09-30 14:20 UTC, TineZata requested changes
Generally good... a few minor changes.

2020-09-30 14:20 UTC, TineZata commented on .gitignore
> +.vscode/**
:thumbsup:

2020-09-30 14:20 UTC, TineZata commented on pixciApp/Makefile
> +# DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard op))
Probably best to just delete this

2020-09-30 14:20 UTC, TineZata commented on pixciApp/src/pixci.cpp
> +
:thumbsup:

2020-09-30 14:20 UTC, TineZata commented on pixciApp/src/pixci.cpp
> +            test = pxd_readuchar(UNIT, buf, 0, 0, sizeX, sizeY, (epicsUInt8*)pImage->pData, dims[0] * dims[1] * sizeof(epicsUInt16), "GRAY");
using `sizeof(epicsUInt16)`, should this be `sizeof(epicsUInt8`?

2020-09-30 14:20 UTC, TineZata commented on pixciApp/src/pixci.cpp
> +                break;
```
pxd_videoFormatAsIncludedInit(0);
pxd_videoFormatAsIncluded(0);
```
Can be moved outside switch statement.

2020-10-05 06:23 UTC, subindev-d commented on pixciApp/src/pixci.cpp
> +            test = pxd_readuchar(UNIT, buf, 0, 0, sizeX, sizeY, (epicsUInt8*)pImage->pData, dims[0] * dims[1] * sizeof(epicsUInt16), "GRAY");
yes, its fixed.

2020-10-05 06:31 UTC, subindev-d commented on pixciApp/Makefile
> +# DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard op))
added a make file inside op to solve this issue rather than commenting.

2020-10-05 06:33 UTC, subindev-d commented on pixciApp/src/pixci.cpp
> +                break;
have tried that, 
pxd_videoFormatAsIncludedInit(0);                   
pxd_videoFormatAsIncluded(0);

should be inside same curly braces, otherwise showing error.

2020-10-29 13:26 UTC, TineZata approved these changes

2020-10-29 13:26 UTC, merged